version: "3.1"

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  app:
    container_name: todoApp
    build: .
    # ports:
    #   - "3000:3000"
    environment:
      - PORT=3000
    depends_on:
      - mongo
      # - mongo-express

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: theHinneh
      MONGO_INITDB_ROOT_PASSWORD: theHinneh
    volumes:
      - mongo-db:/data/db

  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: theHinneh
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: theHinneh

volumes:
  mongo-db:
