version: "3"

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  todo-app:
    build: .
    # ports:
    #   - "3000:3000"
    environment:
      - PORT=3000
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=theHinneh
      - MONGO_INITDB_ROOT_PASSWORD=theHinneh
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db:
