version: "3.9"

services:
  nginx:
    ports:
      - "3000:80"

  app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=theHinneh
      - MONGO_PASSWORD=theHinneh
    command: npm start
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=theHinneh
      - MONGO_INITDB_ROOT_PASSWORD=theHinneh
